### ISSUE TITLE
feat(UI/UX Design): convert simple PNG images to SVGs

### ISSUE THREAD

**Issue by ashuvssut** [WalkingPal/walking-pal-web#141]
### Description

There are some PNGs in the webisite like these:
![image](https://user-images.githubusercontent.com/60546840/194330349-377a4a00-225e-427b-a8b0-827e4cf2af31.png)

Create PRs to convert each of these simple PNGs to SVGs (PNGs can not be convert to SVGs. You need to use tools like Adobe Illustrator, figma, etc to design these vector graphics. refer PR #32 for reference --- this PR converted the logo PNG to SVG.)

Create 1 PR for 1 PNG conversion. Multiple contributors can be assigned to this issue. 

⚠**Contributors who are interested, please tell beforehand that which PNG you are going to start working on. This will avoid clashes (possibility of 2 people working on the same PNG conversion). Provide the screenshot of the PNG image so that we can figure out which PNG you are working on**

----------------------------------

# Important points

1. Please refrain from using tools that convert PNGs to SVGs. **YOU HAVE TO DO THIS MANUALLY.**
   - Please work on this ONLY if you know how/want to learn how to create SVGs
2. **We accept 1 PNG conversion per PR.** 
   - **Example**: checkout `footstep2.svg` in this PR: #134
4. Original PNG can be found in [assets/png](https://github.com/WalkingPal/walking-pal-web/tree/dev/assets/png)

## Current Progress

- [x] WalkingPal logo (@KaranSinghBisht #32 )
- [x] [footstep2.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/footstep2.png) (@annalbirena #134)
- [x] [footstep.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/footstep.png) (@annalbirena #167)
- [x] [pin.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/pin.png) (@senali-d #155 )
- [x] [bagpack.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/bagpack.png) (@spoloxs  #168)
- [ ] [404.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/404.png)
- [ ] [clip.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/clip.png)
- [ ] [credit.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/credit.png)
- [ ] [founders-hub.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/founders-hub.png)
- [ ] [promotion.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/promotion.png)
- [ ] [shape1.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/shape1.png)
- [ ] [shopping.png](https://github.com/WalkingPal/walking-pal-web/blob/dev/assets/png/shopping.png)

**Comment by MohamedMetwalli5** [comment]
I would like to work on this issue. 
I would like to choose the pin.png image.

**Comment by spoloxs** [comment]
Can I work on the backpack.png please?

**Comment by ashuvssut** [comment]
@spoloxs yes please!
